### ISSUE TITLE
Uncaught TypeError: this.resultsPaneView.find is not a function

### ISSUE THREAD

**Issue by lacostenycoder** [whoisthecoon/atom-fold-search-results#3]
1. right click on search results
2. click on `Toggle fold results`

Error appears.

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.11.6
**Thrown From**: [fold-search-results](https://github.com/whoisthecoon/atom-fold-search-results) package 1.0.5

### Stack Trace

Uncaught TypeError: this.resultsPaneView.find is not a function

```
At /Users/lacoste/.atom/packages/fold-search-results/lib/ToggleSearchResults.js:57

TypeError: this.resultsPaneView.find is not a function
    at ToggleSearchResults.fold (/packages/fold-search-results/lib/ToggleSearchResults.js:57:46)
    at ToggleSearchResults.toggle (/packages/fold-search-results/lib/ToggleSearchResults.js:90:40)
    at HTMLDivElement.toggle (/packages/fold-search-results/lib/atom-fold-search-results.js:9:13)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:3:59)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (/app.asar/src/atom-environment.js:1185:28)
    at EventEmitter.outerCallback (/app.asar/src/application-delegate.js:325:25)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -2:44 project-find:show (input.hidden-input)
     -2:43.6.0 core:paste (input.hidden-input)
     -2:43.1.0 core:confirm (input.hidden-input)
     -2:39.3.0 atom-minify:close-panel (div.results-view.focusable-panel)
     -2:39.3.0 core:cancel (div.results-view.focusable-panel)
     -2:38.4.0 atom-minify:close-panel (div.results-view.focusable-panel)
     -2:38.4.0 core:cancel (div.results-view.focusable-panel)
     -2:20.9.0 atom-minify:close-panel (div.results-view.focusable-panel)
     -2:20.9.0 core:cancel (div.results-view.focusable-panel)
     -2:20.4.0 core:close (div.results-view.focusable-panel)
     -2:17.7.0 project-find:show (input.hidden-input)
     -2:16.1.0 core:confirm (input.hidden-input)
     -0:10.5.0 fold-search-results:toggle (li.search-result.list-item.selected)
```

### Non-Core Packages

```
2-dark-syntax 1.1.0 
advanced-open-file 0.16.6 
atom-minify 0.8.0 
atom-wrap-in-tag 0.6.0 
autoclose-html 0.23.0 
Base16-Chalk-Dark 0.1.0 
breezy-dark-ui 0.1.0 
busy-signal 1.3.0 
change-case 0.6.5 
color-picker 2.2.5 
custom-title 1.0.1 
dead-simple-light-syntax 0.1.0 
emmet 2.4.3 
erb-helper 1.1.0 
file-icons 2.1.3 
fold-search-results 1.0.5 
git-blame 1.0.1 
git-control 0.9.0 
git-plus 7.5.0 
git-split-diff-hyperclick 0.3.12 
git-time-machine 1.5.9 
gl-light-syntax 2.2.0 
gloom 0.4.13 
hyperclick 0.0.40 
intentions 1.1.2 
linter 2.1.4 
linter-ruby 1.2.5 
linter-ui-default 1.2.3 
steam-pirate-syntax 0.4.0 
monokai-one-dark-vivid-syntax 1.4.0 
newbound-light-syntax 1.3.0 
nucleus-dark-ui 0.11.17 
oceanic-next 1.0.0 
one-dark-dim-syntax 0.1.0 
one-dark-material-syntax 1.0.3 
one-dark-vivid-syntax 1.7.1 
platformio-ide-terminal 2.5.0 
pristine-ui 1.0.15 
rails-partials 0.9.2 
rails-rspec 0.3.2 
rails-transporter 1.6.5 
relative-numbers 0.7.1 
ruby-test 1.0.1 
script 3.14.1 
set-syntax 0.3.2 
snow-dark-syntax 0.1.1 
specs undefined 
split-diff 1.3.0 
spring-dark-syntax 0.0.4 
steam-pirate-syntax 0.4.0 
styles undefined 
titan-dark-syntax 2.0.0 
tree-view-breadcrumb 0.8.1 
tree-view-git-branch 0.1.2 
two-light-ui 1.1.3 
vim-mode-plus 0.89.0 
vim-mode-plus-ex-mode 0.9.0 
vim-mode-plus-keymaps-for-surround 0.2.1 
vivid-syntax 2.1.0 
vmp-gutter-annotate-mark 0.3.2 
```

**Comment by a7madgamal** [comment]
same here

**Comment by whoisthecoon** [comment]
Hi,

I don't plan to fix this myself, I don't have the time, and Atom added buttons that do the exact same job. 

If one of you guys wants to do it, PRs are welcome!

**Comment by a7madgamal** [comment]
cool I didn't notice that!
no need to bother then, If I were you I would deprecate this package and notify users about this native button in the readme.
a final update with a warning notification to remove the package would be a nice idea too to save your users some resources (and save yourself lots of issues here).

Whatever you decide to do, thanks alot for this package 👍

**Comment by lacostenycoder** [comment]
Since Atom core adds this functionality, I see no reason for this package and therefore closing this issue.  +1 to deprecate package, and thanks for making it as it was useful prior to this bug.
